spring:
  cache:
    type: caffeine
    cache-names: moviesCache
    caffeine:
      spec: maximumSize=10,expireAfterWrite=60s
  data:
    mongodb:
      auto-index-creation: true
      uri: "mongodb://leonardo:123456@localhost:27017/movies?authSource=admin&serverSelectionTimeoutMS=1000&connectTimeoutMS=1000"
  integration:
    tmdb:
      url: https://api.themoviedb.org/3/
      bearer: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2YmY4ZjI4OTM0NzE4MGQ5YzhiNzliZTM5Y2FkYmQ5NiIsIm5iZiI6MTcyODA4NzI0NC44MTE0OCwic3ViIjoiNjA5YTYxNzUyODNlZDkwMDNjNmZlMTEzIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.IaEeZBuIP7DdvQ4C0ZaT4zY6bFwN3r-iFSHccLP0qsE
      config:
        include-video: false
        include-adult: false
        language: pt-BR
        keywords-page: 1
        recommended-page: 1
server:
  port: 8090
resilience4j:
  circuitbreaker:
    instances:
      movieDetailCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 10
        ignoreExceptions:
          - com.br.app.movie.tmdb.java.app.exceptions.ResourceNotFoundException
  timelimiter:
    instances:
      movieBackdropsTimeLimiter:
        timeoutDuration: 1s
  ratelimiter:
    instances:
      movieKeywordsRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 20s
        timeoutDuration: 2s
  retry:
    instances:
      movieRecommendedRetry:
        maxAttempts: 3
        waitDuration: 2s
logging:
  level:
    io.github.resilience4j: DEBUG